inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.5.3

  # 除外ディレクトリ
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*
    - app/models/user.rb
    - db/seeds.rb
    - spec/models/user_spec.rb
    - spec/spec_helper.rb

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# update_attributeについて
Rails/ActiveRecordAliases:
  Enabled: false

# pathの書き方を/path/aa/bbで書ける
Rails/FilePath:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

GlobalVars:
  AllowedVariables: [$worker, $app_dir, $std_log, $timeout, $listen, $pid]

Naming/VariableNumber:
  Enabled: false
