version: '3'
services:
  # データベースのサービス定義
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - '3306:3306'

  # アプリケーションサーバーのサービス定義
  web:
    build: .
    # puma使用
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_name
      - bundle:/usr/local/bundle:delegated
      - tmp-data:/app_name/tmp/sockets
      - public-data:/app_name/public
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    links:
      - db
    environment:
    - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none

volumes:
  public-data:
  tmp-data:
  mysql-data:
  db-volume:
  bundle:

# heroku版(Puma)
# version: '3'
# services:
#   db:
#     image: mysql:5.7
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: root
#     ports:
#       - "3306:3306"

#   web:
#     build: .
#     command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#     stdin_open: true
#     tty: true
#     volumes:
#       - .:/app_name
#     ports:
#       - "3000:3000"
#     links:
#       - db
#     environment:
#     - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

#   selenium_chrome:
#     image: selenium/standalone-chrome-debug
#     logging:
#       driver: none
