version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    # railsコマンドの前にpidファイルを削除
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - .:/app_name
    ports:
      # "host-port(80):container-port(3000)" => EC2で80番portにリクエストが来ると、内部で3000番portに渡してあげる
      - "80:3000"
    links:
      - db
    environment:
    - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"

  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
